version: '3.1'
services:
  app:
    image: pesbuk:1.7
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: dbsosmed
      MYSQL_USER: devopscilsy
      MYSQL_PASSWORD: 1234567890
    volumes:
      - db:/var/lib/mysql
      # - ./.server:/docker-entrypoint-initdb.d

volumes:
  db: